# Generated by Django 2.2.7 on 2019-12-04 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='heading',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
